# Generated by Django 5.2.4 on 2025-07-23 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_otp_sent',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_created_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_resend_count',
        ),
    ]
